---
- name: Check if Splunk is already installed
  yum: name=splunk state=present
  register: splunk_installed_result
  ignore_errors: yes

- name: Check if Splunk is running
  shell: /opt/splunk/bin/splunk status
  register: splunk_running
  ignore_errors: yes

- name: Stop splunk service
  shell: /opt/splunk/bin/splunk stop
  register: splunk_stop
  ignore_errors: yes
  
- name: uploading splunk installation package
  copy: src="{{ splunk_file_path }}/{{ splunk_package_file }}"
        dest= "{{ splunk_installation_temp_path }}/{{ splunk_package_file }}"
        
# un comment this task as per requirement
#- name: Curl the package
#  get_url:
#    url:splunk_package_name.rpm
#     dest:/local/lfs2/opt/ (or)  "{{ splunk_installation_temp_path }}/{{ splunk_package_file }}"
#     mode="0755"

- name: Check that Splunk installer binary exists
  state: path="{{ splunk_installation_temp_path }}/{{ splunk_package_file }}"
  register: splunk_installer_present

- name: Install Splunk server package
  tags:
   - install
  yum: pkg="{{ splunk_installation_temp_path }}/{{ splunk_package_file }}" state=installed
  when: splunk_installer_present.stat.exists == true

- name: Start splunk service
  shell: /opt/splunk/bin/splunk start --accept-license --answer-yes
  register: splunk_start
  ignore_errors: yes
  
- name: Set auto start after every boot
  shell: /opt/splunk/bin/splunk enable boot-start
- name: Clean up splunk installation package RPM file

  shell: rm -rf /"{{ splunk_installation_temp_path }}/{{ splunk_package_file }}"
  when: splunk_installer_present.stat.exists == true

